const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const settings={mode:localStorage.getItem('osc.mode')||'offline',url:localStorage.getItem('osc.url')||'',room:localStorage.getItem('osc.room')||'',localUrl:localStorage.getItem('osc.localUrl')||'',sound:localStorage.getItem('osc.sound')!=='false',wake:localStorage.getItem('osc.wake')!=='false'};
let socket=null,retryTimer=null,sent=0,audio=null,wakeLock=null,lastTick=new Map(),pending=new Map(),raf=0;
const dialog=$('#settingsDialog'),modeInput=$('#connectionMode'),serverUrl=$('#serverUrl'),roomCode=$('#roomCode'),localUrl=$('#localUrl'),soundEnabled=$('#soundEnabled'),wakeEnabled=$('#wakeLockEnabled'),errorText=$('#settingsError');
modeInput.value=settings.mode;serverUrl.value=settings.url;roomCode.value=settings.room;localUrl.value=settings.localUrl;soundEnabled.checked=settings.sound;wakeEnabled.checked=settings.wake;
function setStatus(state,detail,connected=false){$('#statusText').textContent=state;$('#roomText').textContent=detail;$('#statusDot').classList.toggle('connected',connected);$('#connectButton').textContent=connected?'切断':settings.mode==='offline'?'設定':'接続'}
function showModeFields(){const m=modeInput.value;$('#cloudFields').classList.toggle('hidden',m!=='cloud');$('#localFields').classList.toggle('hidden',m!=='local');errorText.textContent=''}
modeInput.addEventListener('change',showModeFields);showModeFields();
function normalizeCloudUrl(url){url=url.trim().replace(/\/$/,'');if(url.startsWith('https://'))url='wss://'+url.slice(8);else if(url.startsWith('http://'))url='ws://'+url.slice(7);return url}
function endpoint(){if(settings.mode==='cloud')return `${normalizeCloudUrl(settings.url)}/room/${encodeURIComponent(settings.room)}?role=controller`;if(settings.mode==='local'){if(settings.localUrl.trim())return settings.localUrl.trim();if(location.protocol==='http:')return `ws://${location.host}/ws`}return ''}
function connect(){if(settings.mode==='offline'){disconnect(false);setStatus('オフライン','UI確認モード');dialog.showModal();return}const ep=endpoint();if(!ep){dialog.showModal();errorText.textContent='接続先を入力してください。';return}if(location.protocol==='https:'&&ep.startsWith('ws://')){dialog.showModal();errorText.textContent='HTTPSページからローカルws://へは接続できません。PCの http://IP:8080 を開いてください。';return}disconnect(false);setStatus('接続中…',settings.mode==='cloud'?`ROOM ${settings.room}`:'同一LAN');try{socket=new WebSocket(ep);socket.onopen=()=>setStatus('接続済み',settings.mode==='cloud'?`ROOM ${settings.room}`:'同一LAN・直接接続',true);socket.onclose=()=>{setStatus('未接続','5秒後に再接続します');retryTimer=setTimeout(connect,5000)};socket.onerror=()=>setStatus('接続エラー','接続先とPC側サーバーを確認');socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='fader')applyRemote(m)}catch{}}}catch{setStatus('接続エラー','WebSocket URLが不正です')}}
function disconnect(manual=true){clearTimeout(retryTimer);retryTimer=null;if(socket){socket.onclose=null;socket.close();socket=null}if(manual)setStatus(settings.mode==='offline'?'オフライン':'未接続',settings.mode==='offline'?'UI確認モード':'手動で切断しました')}
function send(channel,value,final=false){pending.set(channel,{type:'fader',channel,value:value/100,final,at:Date.now()});if(!raf)raf=requestAnimationFrame(flush)}
function flush(){raf=0;if(socket?.readyState!==WebSocket.OPEN){pending.clear();return}for(const msg of pending.values()){socket.send(JSON.stringify(msg));sent++}pending.clear()}
async function unlockAudio(){if(!settings.sound)return;audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')try{await audio.resume()}catch{}}
document.addEventListener('pointerdown',unlockAudio,{passive:true});
function playTick(strong){if(!settings.sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=strong?820:650;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.03);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.035)}
function tick(card,ch,value){const step=Math.round(value/5);if(lastTick.get(ch)===step)return;lastTick.set(ch,step);card.classList.add('tick');setTimeout(()=>card.classList.remove('tick'),70);playTick(step%5===0)}
const EDGE=28;
function positionThumb(card,value){const zone=card.querySelector('.fader-zone'),thumb=card.querySelector('.custom-thumb');if(!thumb)return;const travel=Math.max(1,zone.clientHeight-EDGE*2);thumb.style.top=`${EDGE+(100-value)/100*travel}px`}
function updateCard(card,value,remote=false){value=Math.max(0,Math.min(100,Number(value)));const slider=card.querySelector('.vertical-fader'),out=card.querySelector('output'),zone=card.querySelector('.fader-zone'),ch=Number(card.dataset.channel);slider.value=value;out.textContent=Math.round(value);zone.setAttribute('aria-valuenow',Math.round(value));positionThumb(card,value);tick(card,ch,value);if(!remote)send(ch,value,false)}
function pointerValue(zone,y){const r=zone.getBoundingClientRect(),p=Math.max(EDGE,Math.min(r.height-EDGE,y-r.top));return Math.round((1-(p-EDGE)/Math.max(1,r.height-EDGE*2))*100)}
$$('.fader-card').forEach(card=>{const zone=card.querySelector('.fader-zone'),slider=card.querySelector('.vertical-fader'),ch=Number(card.dataset.channel);zone.insertAdjacentHTML('beforeend','<div class="custom-track" aria-hidden="true"></div><div class="custom-thumb" aria-hidden="true"></div>');zone.tabIndex=0;zone.setAttribute('role','slider');zone.setAttribute('aria-label',slider.getAttribute('aria-label'));zone.setAttribute('aria-valuemin','0');zone.setAttribute('aria-valuemax','100');let drag=false;const move=e=>{if(!drag)return;e.preventDefault();updateCard(card,pointerValue(zone,e.clientY))};zone.addEventListener('pointerdown',e=>{drag=true;zone.setPointerCapture(e.pointerId);move(e)});zone.addEventListener('pointermove',move);zone.addEventListener('pointerup',e=>{if(!drag)return;move(e);drag=false;send(ch,Number(slider.value),true)});zone.addEventListener('pointercancel',()=>drag=false);zone.addEventListener('keydown',e=>{let v=Number(slider.value);if(e.key==='ArrowUp'||e.key==='ArrowRight')v++;else if(e.key==='ArrowDown'||e.key==='ArrowLeft')v--;else if(e.key==='Home')v=0;else if(e.key==='End')v=100;else return;e.preventDefault();updateCard(card,v);send(ch,v,true)});card.querySelector('.reset-button').onclick=()=>{updateCard(card,50);send(ch,50,true)};updateCard(card,slider.value,true)});
function applyRemote(m){const card=$(`.fader-card[data-channel="${Number(m.channel)}"]`);if(card)updateCard(card,Number(m.value)*100,true)}
function positionAll(){$$('.fader-card').forEach(c=>positionThumb(c,c.querySelector('.vertical-fader').value))}new ResizeObserver(positionAll).observe($('.faders'));
async function requestWake(){if(wakeLock||!settings.wake||!('wakeLock'in navigator))return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>wakeLock=null)}catch{}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')requestWake()});
$('#settingsButton').onclick=()=>dialog.showModal();$('#closeSettings').onclick=()=>{errorText.textContent='';dialog.close()};
$('#connectButton').onclick=()=>socket?.readyState===WebSocket.OPEN?disconnect():connect();
$('#resetAllButton').onclick=()=>$$('.fader-card').forEach((c,i)=>{updateCard(c,50);send(i+1,50,true)});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const mode=modeInput.value;if(mode==='cloud'&&(!serverUrl.value.trim()||!roomCode.value.trim())){errorText.textContent='クラウドURLとルームコードを入力してください。';return}if(mode==='local'&&!localUrl.value.trim()&&location.protocol!=='http:'){errorText.textContent='ローカルURLを入力するか、PCのローカルページを開いてください。';return}Object.assign(settings,{mode,url:serverUrl.value.trim(),room:roomCode.value.trim(),localUrl:localUrl.value.trim(),sound:soundEnabled.checked,wake:wakeEnabled.checked});for(const[k,v]of Object.entries(settings))localStorage.setItem(`osc.${k==='localUrl'?'localUrl':k}`,String(v));dialog.close();requestWake();if(mode==='offline'){disconnect(false);setStatus('オフライン','UI確認モード')}else connect()});
setInterval(()=>{$('#sendRate').textContent=`${sent} msg/s`;sent=0},1000);
if('serviceWorker'in navigator&&location.protocol==='https:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
setStatus(settings.mode==='offline'?'オフライン':'未接続',settings.mode==='offline'?'UI確認モード':settings.mode==='local'?'同一LANモード':settings.room?`ROOM ${settings.room}`:'接続設定を開いてください');
