const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ADDRESS_RE=/^\/[a-z0-9]+(?:\/[a-z0-9-]+)*$/;
const defaults={schemaVersion:6,uiMode:'simple',connectionMode:'offline',serverUrl:'',roomCode:'',localUrl:'',oscHost:'127.0.0.1',oscPort:3336,easeMs:60,channelCount:8,sound:true,wake:true,startLocked:false,dcaMaster:100,patches:[]};
function defaultPatch(i){return{label:`CH ${i+1}`,address:`/webfader/ch-${String(i+1).padStart(2,'0')}`,min:0,max:100,type:'float',dcaLevel:0}}
let saved={};try{saved=JSON.parse(localStorage.getItem('oscConsoleV2')||'{}')}catch{}const savedVersion=+saved.schemaVersion||0;let cfg={...defaults,...saved};if(savedVersion<4&&+cfg.easeMs>=180)cfg.easeMs=60;cfg.schemaVersion=6;
for(let i=0;i<32;i++){const old=cfg.patches[i]||{};cfg.patches[i]={...defaultPatch(i),...old};if(old.dcaLevel==null)cfg.patches[i].dcaLevel=old.dca&&old.dca!=='none'?100:0;cfg.patches[i].dcaLevel=Math.max(0,Math.min(100,+cfg.patches[i].dcaLevel||0))}
const fixedCloud=window.OSC_CLOUD_CONFIG||{},fixedCloudReady=!!fixedCloud.workerUrl&&!fixedCloud.workerUrl.includes('REPLACE-WITH');if(fixedCloudReady)Object.assign(cfg,{connectionMode:'cloud',serverUrl:fixedCloud.workerUrl,roomCode:fixedCloud.roomCode});
let socket=null,retryTimer=null,sent=0,audio=null,wakeLock=null,locked=!!cfg.startLocked,currentView='channels',bank=0,lastFrame=performance.now(),activeValueKey=null,activeValueMode='channel';
const states=Array.from({length:32},(_,i)=>{const p=cfg.patches[i],v=(+p.min+ +p.max)/2;return{current:v,target:v,sentAt:0}}),dcaSendStates=Array.from({length:32},(_,i)=>({current:+cfg.patches[i].dcaLevel||0,target:+cfg.patches[i].dcaLevel||0,sentAt:0})),dcaMaster={current:Math.max(0,Math.min(100,+cfg.dcaMaster||100)),target:Math.max(0,Math.min(100,+cfg.dcaMaster||100))};
function save(){localStorage.setItem('oscConsoleV2',JSON.stringify(cfg))}
function setStatus(t,d,ok=false){$('#statusText').textContent=t;$('#statusDetail').textContent=d;$('#statusDot').classList.toggle('connected',ok);$('#connectButton').textContent=ok?'切断':cfg.connectionMode==='offline'?'設定':'接続'}
function cloudEndpoint(){let u=cfg.serverUrl.trim().replace(/\/$/,'').replace(/^https:/,'wss:').replace(/^http:/,'ws:');return `${u}/room/${encodeURIComponent(cfg.roomCode)}?role=controller`}
function endpoint(){if(cfg.connectionMode==='cloud')return cloudEndpoint();if(cfg.connectionMode==='local')return cfg.localUrl.trim()||(location.protocol==='http:'?`ws://${location.host}/ws`:'');return''}
function disconnect(manual=true){clearTimeout(retryTimer);if(socket){socket.onclose=null;socket.close();socket=null}if(manual)setStatus(cfg.connectionMode==='offline'?'オフライン':'未接続',cfg.connectionMode==='offline'?'UI確認モード':'切断しました')}
function connect(){if(cfg.connectionMode==='offline'){disconnect(false);setStatus('オフライン','UI確認モード');return}const ep=endpoint();if(!ep){openSettings('basic','接続先を設定してください。');return}disconnect(false);setStatus('中継接続中…','Cloudflare Worker');try{socket=new WebSocket(ep);socket.onopen=()=>setStatus('PC確認中','中継サーバー接続済み');socket.onclose=()=>{setStatus('中継未接続','5秒後に再接続');retryTimer=setTimeout(connect,5000)};socket.onerror=()=>setStatus('接続エラー','Worker URLを確認');socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='bridge-status')setStatus(m.online?'PC接続済み':'PCオフライン',m.online?'Unityへ送信できます':'Bridgeを起動してください',m.online);else if(m.type==='osc'&&Number.isInteger(m.channel)&&cfg.patches[m.channel]){states[m.channel].target=+m.baseValue||+m.value;states[m.channel].current=states[m.channel].target}}catch{}}}catch{setStatus('接続エラー','Worker URLが不正です')}}
function effective(i){const b=states[i].current,a=dcaSendStates[i].current/100,m=dcaMaster.current/100;return b*(1-a+a*m)}
function validPatch(p){return ADDRESS_RE.test(p.address)&&Number.isFinite(+p.min)&&Number.isFinite(+p.max)&&+p.max>+p.min}
function emit(i,final=false){const p=cfg.patches[i];if(!validPatch(p))return console.warn('[OSC Warning] 不正なパッチをスキップ:',p);const value=p.type==='int'?Math.round(effective(i)):effective(i),msg={type:'osc',channel:i,address:p.address,value,baseValue:states[i].current,dcaLevel:dcaSendStates[i].current,dcaMaster:dcaMaster.current,valueType:p.type,oscHost:cfg.oscHost,oscPort:+cfg.oscPort,final,at:Date.now()};if(socket?.readyState===WebSocket.OPEN){socket.send(JSON.stringify(msg));sent++}}
async function unlockAudio(){if(!cfg.sound)return;audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')try{await audio.resume()}catch{}}
function tickSound(strong=false){if(!cfg.sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=strong?820:650;g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.028);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.03)}document.addEventListener('pointerdown',unlockAudio,{passive:true});
function fmt(v,p){return p.type==='int'?String(Math.round(v)):Math.abs(v)>=10?v.toFixed(1).replace('.0',''):v.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
function norm(i,v){const p=cfg.patches[i];return Math.max(0,Math.min(1,(v-p.min)/(p.max-p.min)))}
function cardHtml(key,label,value,dcaMode=false){return `<article class="fader-card${locked?' locked':''}${dcaMode?' dca-mode':''}" data-key="${key}"><div class="fader-heading"><span>${label}</span><output tabindex="0">${value}</output></div><div class="effective">${dcaMode?'DCA影響率':' '}</div><div class="fader-zone" role="slider" tabindex="0"><div class="ticks"></div><div class="track"></div><div class="thumb"></div></div><button class="reset-button">MAX</button></article>`}
function render(){const count=cfg.uiMode==='simple'?4:Math.max(1,Math.min(32,+cfg.channelCount||4));$('#customToolbar').classList.toggle('hidden',cfg.uiMode!=='custom');const pages=Math.ceil(count/4);bank=Math.min(bank,Math.max(0,pages-1));$('#bankLabel').textContent=`BANK ${bank+1}/${pages}`;const dm=currentView==='dca'&&cfg.uiMode==='custom';$('#dcaMasterBar').classList.toggle('hidden',!dm);$('#dcaMaster').value=Math.round(dcaMaster.current);$('#dcaMasterOutput').textContent=Math.round(dcaMaster.current);let h='',start=cfg.uiMode==='simple'?0:bank*4;for(let i=start;i<Math.min(start+4,count);i++)h+=dm?cardHtml(`dca-ch-${i}`,cfg.patches[i].label,Math.round(dcaSendStates[i].current),true):cardHtml(`ch-${i}`,cfg.patches[i].label,fmt(states[i].current,cfg.patches[i]));$('#faders').innerHTML=h;bindCards();updateLockUI()}
function setThumb(card,n){const z=card.querySelector('.fader-zone'),t=card.querySelector('.thumb'),edge=28;t.style.top=`${edge+(1-n)*Math.max(1,z.clientHeight-edge*2)}px`}
function refreshCard(key){const c=$(`.fader-card[data-key="${key}"]`);if(!c)return;if(key.startsWith('dca-ch-')){const i=+key.slice(7),p=cfg.patches[i];c.querySelector('output').textContent=Math.round(dcaSendStates[i].current);c.querySelector('.effective').textContent=`BASE ${fmt(states[i].current,p)} → ${fmt(effective(i),p)}`;setThumb(c,dcaSendStates[i].current/100)}else{const i=+key.slice(3),p=cfg.patches[i];c.querySelector('output').textContent=fmt(states[i].current,p);c.querySelector('.effective').textContent=dcaSendStates[i].current>0?`→ ${fmt(effective(i),p)} / DCA ${Math.round(dcaSendStates[i].current)}%`:' ';setThumb(c,norm(i,states[i].current))}}
function setTarget(key,ratio){ratio=Math.max(0,Math.min(1,ratio));if(key.startsWith('dca-ch-'))dcaSendStates[+key.slice(7)].target=ratio*100;else{const i=+key.slice(3),p=cfg.patches[i];states[i].target=+p.min+ratio*(+p.max-+p.min)}}
function bindCards(){$$('.fader-card').forEach(card=>{const key=card.dataset.key,z=card.querySelector('.fader-zone');refreshCard(key);let drag=false,lastStep=-1;const move=e=>{if(!drag||locked)return;e.preventDefault();const r=z.getBoundingClientRect(),y=e.clientY-r.top,edge=28,cy=Math.max(edge,Math.min(r.height-edge,y)),ratio=1-(cy-edge)/Math.max(1,r.height-edge*2);setTarget(key,ratio);const step=Math.floor(ratio*20);if(step!==lastStep){lastStep=step;tickSound(false)}};z.onpointerdown=e=>{if(locked)return;drag=true;z.setPointerCapture(e.pointerId);move(e)};z.onpointermove=move;z.onpointerup=e=>{if(!drag)return;move(e);drag=false;if(key.startsWith('dca-ch-')){const i=+key.slice(7);cfg.patches[i].dcaLevel=dcaSendStates[i].target;save();emit(i,true)}else emit(+key.slice(3),true)};z.onpointercancel=z.onpointerup;card.querySelector('.reset-button').onclick=()=>{if(locked)return;tickSound(true);if(key.startsWith('dca-ch-')){const i=+key.slice(7);dcaSendStates[i].target=dcaSendStates[i].current=100;cfg.patches[i].dcaLevel=100;save();refreshCard(key);emit(i,true)}else{const i=+key.slice(3),p=cfg.patches[i];states[i].target=states[i].current=+p.max;refreshCard(key);emit(i,true)}};card.querySelector('output').onclick=()=>{if(locked)return;openValue(key.startsWith('dca-ch-')?+key.slice(7):+key.slice(3),key.startsWith('dca-ch-')?'dca':'channel')}})}
function animate(now){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;const tau=Math.max(0,+cfg.easeMs)/1000,a=tau<=0?1:1-Math.exp(-dt/tau),count=Math.min(32,+cfg.channelCount||4);for(let i=0;i<count;i++){const s=states[i],b=s.current;s.current+=(s.target-s.current)*a;if(Math.abs(s.target-s.current)<1e-4)s.current=s.target;if(Math.abs(s.current-b)>1e-5){refreshCard(`ch-${i}`);refreshCard(`dca-ch-${i}`);if(now-s.sentAt>33){emit(i);s.sentAt=now}}const d=dcaSendStates[i],db=d.current;d.current+=(d.target-d.current)*a;if(Math.abs(d.target-d.current)<.01)d.current=d.target;if(Math.abs(d.current-db)>.001){refreshCard(`dca-ch-${i}`);refreshCard(`ch-${i}`);if(now-d.sentAt>33){emit(i);d.sentAt=now}}}requestAnimationFrame(animate)}requestAnimationFrame(animate);
function updateLockUI(){$('#lockButton').textContent=locked?'🔒':'🔓';$$('.fader-card').forEach(c=>c.classList.toggle('locked',locked));$('#dcaMaster').disabled=locked;$('#dcaMasterMax').disabled=locked}$('#lockButton').onclick=()=>{locked=!locked;updateLockUI()};
function fillSettings(){$('#uiMode').value=cfg.uiMode;$('#connectionMode').value=cfg.connectionMode;$('#serverUrl').value=cfg.serverUrl;$('#roomCode').value=cfg.roomCode;$('#localUrl').value=cfg.localUrl;$('#oscHost').value=cfg.oscHost;$('#oscPort').value=cfg.oscPort;$('#easeMs').value=cfg.easeMs;$('#easeOutput').textContent=`${cfg.easeMs} ms`;$('#channelCount').value=cfg.channelCount;$('#soundEnabled').checked=cfg.sound;$('#startLocked').checked=cfg.startLocked;$('#wakeEnabled').checked=cfg.wake;toggleConnectionFields();buildPatchList();if(fixedCloudReady){$('#connectionMode').closest('label').classList.add('hidden');$('#cloudFields').classList.add('hidden');$('#localFields').classList.add('hidden')}}
function toggleConnectionFields(){const m=$('#connectionMode').value;$('#cloudFields').classList.toggle('hidden',m!=='cloud');$('#localFields').classList.toggle('hidden',m!=='local')}
function buildPatchList(){const n=Math.max(4,Math.min(32,+$('#channelCount').value||4));let h='';for(let i=0;i<n;i++){const p=cfg.patches[i];h+=`<details class="patch-row" data-i="${i}" ${i<2?'open':''}><summary>${p.label}　${p.address}</summary><div class="patch-grid"><label>表示名<input class="p-label" type="text" value="${p.label}"></label><label class="wide">Address<input class="p-address" type="text" value="${p.address}"></label><label>最小値<input class="p-min" type="number" step="any" value="${p.min}"></label><label>最大値<input class="p-max" type="number" step="any" value="${p.max}"></label><label>型<select class="p-type"><option value="float" ${p.type==='float'?'selected':''}>float</option><option value="int" ${p.type==='int'?'selected':''}>int</option></select></label></div></details>`}$('#patchList').innerHTML=h}
function openSettings(tab='basic',err=''){fillSettings();$$('.settings-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab-panel').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==tab));$('#settingsError').textContent=err;$('#settingsDialog').showModal()}
$('#settingsButton').onclick=()=>openSettings();$('#closeSettings').onclick=()=>$('#settingsDialog').close();$('#connectionMode').onchange=toggleConnectionFields;$('#easeMs').oninput=e=>$('#easeOutput').textContent=`${e.target.value} ms`;$('#channelCount').onchange=buildPatchList;$$('.settings-tabs button').forEach(b=>b.onclick=()=>{$$('.settings-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-panel').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==b.dataset.tab))});
$('#settingsForm').onsubmit=e=>{e.preventDefault();const next={uiMode:$('#uiMode').value,connectionMode:$('#connectionMode').value,serverUrl:$('#serverUrl').value.trim(),roomCode:$('#roomCode').value.trim(),localUrl:$('#localUrl').value.trim(),oscHost:$('#oscHost').value.trim(),oscPort:+$('#oscPort').value,easeMs:+$('#easeMs').value,channelCount:Math.max(1,Math.min(32,+$('#channelCount').value||4)),sound:$('#soundEnabled').checked,startLocked:$('#startLocked').checked,wake:$('#wakeEnabled').checked};let er='';if(!next.oscHost||next.oscPort<1||next.oscPort>65535)er='送信先IPとPortを確認してください。';$$('.patch-row').forEach(row=>{const i=+row.dataset.i,old=cfg.patches[i],p={...old,label:row.querySelector('.p-label').value.trim()||`CH ${i+1}`,address:row.querySelector('.p-address').value.trim(),min:+row.querySelector('.p-min').value,max:+row.querySelector('.p-max').value,type:row.querySelector('.p-type').value};if(!validPatch(p))er=`CH ${i+1} のAddressまたは範囲が不正です。`;cfg.patches[i]=p});if(er){$('#settingsError').textContent=er;return}Object.assign(cfg,next);save();$('#settingsDialog').close();bank=0;currentView='channels';$$('.segmented button').forEach(x=>x.classList.toggle('active',x.dataset.view==='channels'));render();locked=cfg.startLocked;updateLockUI();connect();requestWake()};
function openValue(i,mode='channel'){activeValueKey=i;activeValueMode=mode;const p=cfg.patches[i],d=mode==='dca';$('#valueTitle').textContent=d?`${p.label} DCA影響率`:`${p.label} の値`;$('#directValue').value=d?Math.round(dcaSendStates[i].target):fmt(states[i].target,p);$('#directValue').min=d?0:p.min;$('#directValue').max=d?100:p.max;$('#valueRange').textContent=d?'範囲: 0 ～ 100%':`範囲: ${p.min} ～ ${p.max} / ${p.type}`;$('#valueError').textContent='';$('#valueDialog').showModal();setTimeout(()=>$('#directValue').select(),50)}
$('#closeValue').onclick=()=>$('#valueDialog').close();$('#valueForm').onsubmit=e=>{e.preventDefault();const i=activeValueKey,p=cfg.patches[i],d=activeValueMode==='dca',min=d?0:+p.min,max=d?100:+p.max,v=+$('#directValue').value;if(!Number.isFinite(v)||v<min||v>max){$('#valueError').textContent='範囲内の数値を入力してください。';return}if(d){dcaSendStates[i].target=dcaSendStates[i].current=v;cfg.patches[i].dcaLevel=v;save()}else states[i].target=states[i].current=p.type==='int'?Math.round(v):v;emit(i,true);$('#valueDialog').close();render()};
$$('.segmented button').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;$$('.segmented button').forEach(x=>x.classList.toggle('active',x===b));render()});$('#prevBank').onclick=()=>{bank=Math.max(0,bank-1);render()};$('#nextBank').onclick=()=>{const pages=Math.ceil(Math.max(1,Math.min(32,+cfg.channelCount||4))/4);bank=Math.min(pages-1,bank+1);render()};$('#connectButton').onclick=()=>socket?.readyState===1?disconnect():cfg.connectionMode==='offline'?openSettings():connect();
$('#dcaMaster').oninput=e=>{if(locked)return;const v=+e.target.value;dcaMaster.current=dcaMaster.target=v;cfg.dcaMaster=v;$('#dcaMasterOutput').textContent=Math.round(v);for(let i=0;i<cfg.channelCount;i++){refreshCard(`dca-ch-${i}`);refreshCard(`ch-${i}`);emit(i)}};$('#dcaMaster').onchange=save;$('#dcaMasterMax').onclick=()=>{if(locked)return;dcaMaster.current=dcaMaster.target=cfg.dcaMaster=100;$('#dcaMaster').value=100;$('#dcaMasterOutput').textContent='100';save();for(let i=0;i<cfg.channelCount;i++){refreshCard(`dca-ch-${i}`);refreshCard(`ch-${i}`);emit(i,true)}};
async function requestWake(){if(wakeLock||!cfg.wake||!('wakeLock'in navigator))return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.onrelease=()=>wakeLock=null}catch{}}document.addEventListener('visibilitychange',()=>document.visibilityState==='visible'&&requestWake());for(const ev of ['gesturestart','gesturechange','gestureend'])document.addEventListener(ev,e=>e.preventDefault(),{passive:false});let lastTouch=0;document.addEventListener('touchend',e=>{const n=Date.now();if(n-lastTouch<320)e.preventDefault();lastTouch=n},{passive:false});document.addEventListener('dblclick',e=>e.preventDefault());setInterval(()=>{$('#sendRate').textContent=`${sent} msg/s`;sent=0},1000);if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js');render();requestWake();if(fixedCloudReady)connect();else setStatus('初期設定が必要','Worker URL未設定');
