const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),dgram=require('dgram');
const {WebSocketServer}=require('ws');
const PORT=Number(process.env.HTTP_PORT||8080),OSC_HOST=process.env.OSC_HOST||'127.0.0.1',OSC_PORT=Number(process.env.OSC_PORT||9000),root=path.resolve(__dirname,'..');
const allowed=new Map([['/','index.html'],['/index.html','index.html'],['/app.js','app.js'],['/styles.css','styles.css'],['/manifest.webmanifest','manifest.webmanifest'],['/sw.js','sw.js'],['/icons/icon-192.png','icons/icon-192.png'],['/icons/icon-512.png','icons/icon-512.png']]);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png'};
const server=http.createServer((req,res)=>{const rel=allowed.get(new URL(req.url,'http://local').pathname);if(!rel){res.writeHead(404);return res.end('Not found')}const file=path.join(root,rel);fs.readFile(file,(e,data)=>{if(e){res.writeHead(500);return res.end('Error')}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data)})});
const wss=new WebSocketServer({server,path:'/ws'}),udp=dgram.createSocket('udp4');
function oscString(s){const raw=Buffer.from(s+'\0');return Buffer.concat([raw,Buffer.alloc((4-raw.length%4)%4)])}function oscPacket(address,value){const f=Buffer.alloc(4);f.writeFloatBE(value);return Buffer.concat([oscString(address),oscString(',f'),f])}
wss.on('connection',ws=>{console.log('Controller connected');ws.on('message',raw=>{try{const m=JSON.parse(String(raw));if(m.type!=='fader'||!Number.isInteger(m.channel))return;const value=Math.max(0,Math.min(1,Number(m.value)));udp.send(oscPacket(`/webfader/${m.channel}`,value),OSC_PORT,OSC_HOST);for(const peer of wss.clients)if(peer!==ws&&peer.readyState===1)peer.send(String(raw))}catch{}});ws.on('close',()=>console.log('Controller disconnected'))});
server.listen(PORT,'0.0.0.0',()=>{console.log(`\nOSC Fader local server: port ${PORT}`);console.log(`OSC output: ${OSC_HOST}:${OSC_PORT}`);for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)console.log(`Open on iPhone: http://${n.address}:${PORT}/`);console.log('Keep this window open.\n')});
